# Generated by Django 4.1.5 on 2023-01-24 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('biceps', models.FloatField()),
                ('triceps', models.FloatField()),
                ('axilar_media', models.FloatField()),
                ('torax', models.FloatField()),
                ('abdominal', models.FloatField()),
                ('suprailiaca', models.FloatField()),
                ('subescapular', models.FloatField()),
                ('coxa', models.FloatField()),
                ('panturrilha', models.FloatField()),
                ('peitoral', models.FloatField()),
                ('abdomen', models.FloatField()),
                ('cintura', models.FloatField()),
                ('quadril', models.FloatField()),
                ('pescoco', models.FloatField()),
                ('coxa_e', models.FloatField()),
                ('coxa_d', models.FloatField()),
                ('panturrilha_e', models.FloatField()),
                ('panturrilha_d', models.FloatField()),
                ('punho_e', models.FloatField()),
                ('punho_d', models.FloatField()),
                ('braco_e', models.FloatField()),
                ('braco_d', models.FloatField()),
                ('antebraco_e', models.FloatField()),
                ('antebraco_d', models.FloatField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.pacientes')),
            ],
        ),
    ]
